embed_url: "https://airtable.com/embed/appo9WyVgYvpap792/shrbAhhxKqvWjaJMs/tblkJ11dnpAvYtRYa"
columns_to_remove:
  - Logo
  - Remote
  - Org Type
  - "Commitment (Beta)"
  - "💰  Salary Range (Beta)"
  - "Report data issue"
